server:
  port: 8989
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jxc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 12345678
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      #空闲连接存活最大时间 180000ms = 180s = 3min
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000

  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/views/
    request-context-attribute: ctx
    settings:
      number_format: 0.##

# mybatis-plus configuration
mybatis-plus:
  # configure Mapper file
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # configure type of the return data aliases(default class name)
  type-aliases-package: com.lzj.admin.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: true

# sql print （方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.lzj.admin.mapper: debug
